version: '3.8'

services:
  atlas-txn-sender:
    platform: linux/amd64
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    
    # image: atlas-txn-sender:local
    # image: rust:1.76-buster
    image: ubuntu:latest
    user: "root"
    group_add:
      - '0'

    ports:
      - 4040:4040
    container_name: atlas-txn-sender
    working_dir: /app
    volumes:
      - type: bind
        source: ${PWD}
        target: /app
