version: '3.8'

services:
  atlas-txn-sender:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile

    image: atlas-txn-sender:d555451
    user: "rustuser"
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: ERROR
      RPC_URL: "https://api.mainnet-beta.solana.com"
      GRPC_URL: http://api.rpcpool.com
      X_TOKEN: d328e5b2-cba1-4848-bbf6-65a77b4fc913
      TPU_CONNECTION_POOL_SIZE: 4
      NUM_LEADERS: 10
      IDENTITY_KEYPAIR_FILE: /app/account1.json
      PORT: 4040


    ports:
      - 4040:4040
      - 7998:7998
    container_name: atlas-txn-sender
    working_dir: /app
    volumes:
      - type: bind
        source: ${PWD}
        target: /app
