instances:

  ## @param use_openmetrics - boolean - optional - default: false
  ## Enable to preview the new version of the check which supports HAProxy version 2+
  ## or environments using the HAProxy exporter.
  ##
  ## OpenMetrics-related options take effect only when this is set to `true`. 
  ##
  ## Uses the latest OpenMetrics V2 implementation for more features and better performance.
  ## Note: To see the configuration options for the OpenMetrics V1 implementation (Agent 7.33 or older),
  ## https://github.com/DataDog/integrations-core/blob/7.33.x/haproxy/datadog_checks/haproxy/data/conf.yaml.example
  #
- use_openmetrics: true  # Enables OpenMetrics V2

  ## @param openmetrics_endpoint - string - optional
  ## The URL exposing metrics in the OpenMetrics format.
  #
  openmetrics_endpoint: http://localhost:4445/metrics

logs:
  - type: udp
    port: 514
    service: atlas
    source: haproxy